### ISSUE TITLE
"String index out of range: -1" with 2 byte tag and zero length

### ISSUE THREAD

**Issue by gissf1** [wcurrie/emv-bertlv-tools#2]
Using the TLV Data mode, it seems a 2 byte tag with zero length causes a "String index out of range: -1" error.

Simplified example TLV Data example to trigger the error:
> 9F4200

I thought that somehow when doing a multi-byte tag, it uses a length calculation to search for the beginning index for the tag value, and it was an off-by-one error, but it handles these fine:
> 9100
> 9F420100
> 9FA20100

So maybe it's something specific to that 9F42 tag?

**Comment by wcurrie** [comment]
I think you're right about being specific to tag 9F42. That's "application currency code". Stack trace shows the failure happens trying to translate a currency code into USD, GPB, etc..:

<pre>
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at io.github.binaryfoo.decoders.CurrencyCodeDecoder.decode(CurrencyCodeDecoder.kt:20)
	at io.github.binaryfoo.TagInfo.decodePrimitiveTlvValue(TagInfo.kt:42)
	at io.github.binaryfoo.decoders.TLVDecoder.decodeTlvs(TLVDecoder.kt:54)
	at io.github.binaryfoo.decoders.TLVDecoder.decode(TLVDecoder.kt:36)
	at io.github.binaryfoo.decoders.TLVDecoder.decode$default(TLVDecoder.kt:34)
	at io.github.binaryfoo.decoders.TLVDecoder.decode(TLVDecoder.kt:14)
	at io.github.binaryfoo.RootDecoder.decode(RootDecoder.kt:29)
	at io.github.binaryfoo.RootDecoder.decode$default(RootDecoder.kt:25)
	at io.github.binaryfoo.controllers.DecodeController.decodeInto(DecodeController.kt:66)
	at io.github.binaryfoo.controllers.DecodeController.decode(DecodeController.kt:25)
</pre>

Should be fixed now. Not a very exciting decode:
![image](https://cloud.githubusercontent.com/assets/2050920/21079912/ad687546-bff4-11e6-9a34-267dd4d0d98a.png)

Fix was https://github.com/binaryfoo/emv-bertlv/commit/21e997a0ee3a5fe9d9510b042074b59a65882bf0
